// GENERATED by delta/build.mjs — do not edit.
//
// Static imports, so the bundler owns the URLs: Next emits each file under
// _next/static/media with a content hash and the basePath already applied,
// and bun's file loader does the same for the bare harness. An import
// resolves to a string under bun and to StaticImageData under Next, which
// is all `staticUrl` exists to paper over.

import { staticUrl } from '@wjh/web/assetUrl'
import colorStrip from './materials/color.jpg'
import normalStrip from './materials/normal.jpg'
import detailStrip from './materials/detail.jpg'
import sky_DaySkyHDRI070B from './skies/DaySkyHDRI070B.jpg'
import sky_DaySkyHDRI071B from './skies/DaySkyHDRI071B.jpg'
import sky_EveningSkyHDRI046B from './skies/EveningSkyHDRI046B.jpg'
import sky_EveningSkyHDRI045B from './skies/EveningSkyHDRI045B.jpg'
import sky_EveningSkyHDRI047B from './skies/EveningSkyHDRI047B.jpg'
import sky_MorningSkyHDRI011B from './skies/MorningSkyHDRI011B.jpg'
import sky_MorningSkyHDRI007B from './skies/MorningSkyHDRI007B.jpg'
import sky_NightSkyHDRI003 from './skies/NightSkyHDRI003.jpg'
import sky_NightSkyHDRI008 from './skies/NightSkyHDRI008.jpg'
import sky_NightSkyHDRI007 from './skies/NightSkyHDRI007.jpg'

export const MATERIAL_URLS = {
  color:  staticUrl(colorStrip),
  normal: staticUrl(normalStrip),
  detail: staticUrl(detailStrip),
}

/** Sky URL by ambientCG asset id. */
export const SKY_URLS: Readonly<Record<string, string>> = {
  DaySkyHDRI070B: staticUrl(sky_DaySkyHDRI070B),
  DaySkyHDRI071B: staticUrl(sky_DaySkyHDRI071B),
  EveningSkyHDRI046B: staticUrl(sky_EveningSkyHDRI046B),
  EveningSkyHDRI045B: staticUrl(sky_EveningSkyHDRI045B),
  EveningSkyHDRI047B: staticUrl(sky_EveningSkyHDRI047B),
  MorningSkyHDRI011B: staticUrl(sky_MorningSkyHDRI011B),
  MorningSkyHDRI007B: staticUrl(sky_MorningSkyHDRI007B),
  NightSkyHDRI003: staticUrl(sky_NightSkyHDRI003),
  NightSkyHDRI008: staticUrl(sky_NightSkyHDRI008),
  NightSkyHDRI007: staticUrl(sky_NightSkyHDRI007),
}
